# wallet-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-deployment
  labels:
    app: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: webdeveloper95/wallet-service:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: wallet-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: wallet-service
  ports:
    - port: 8080
      targetPort: 8080