# wallet-service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: wallet-service-srv
spec:
  type: NodePort
  selector:
    app: wallet-service
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 31000  # Optionally specify a nodePort here, or leave it out for Kubernetes to assign one
