version: "3.8"

services: 
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes: 
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Krneki123!
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=6379

  wallet-api:
    build:
      context: ./BalancerKube.Wallet.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOSTNAME=wallet-api-1 
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - rabbitmq
      - postgres
      - jaeger
  
  wallet-api-2:
    build:
      context: ./BalancerKube.Wallet.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOSTNAME=wallet-api-2 
    ports:
      - "5002:8080"
    depends_on:
      - redis
      - rabbitmq
      - postgres
      - jaeger

  event-generator-api:
    build:
      context: ./BalanceKube.EventGenerator.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOSTNAME=event-generator-api-1
    ports:
      - "5001:8080"
    depends_on:
      - mongo
      - rabbitmq
      - jaeger

  event-generator-api-2:
    build:
      context: ./BalanceKube.EventGenerator.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOSTNAME=event-generator-api-2
    ports:
      - "5003:8080"
    depends_on:
      - mongo
      - rabbitmq
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC endpoint for direct OpenTelemetry export

volumes: 
  rabbitmqdata:
  mongo_data:
  redis_data:
  postgres_data:  